### ISSUE TITLE
document full kubernetes story

### ISSUE THREAD

**Issue by philips** [coreos/torus#130]
- Have instructions for doing the k8s pull secret
- Deploy daemon set
- Talk to etcd and agro machine to mkfs
- Use a flexvolume: https://github.com/kubernetes/kubernetes/tree/master/examples/flexvolume
  - Use a solution like CoreOS Kubernetes does for CNI plugins, using a mount flag
  - https://github.com/coreos/agro/blob/d3872a14f62579ae74b50a40ce64b6b671965e71/cmd/agrom

**Comment by dror-g** [comment]
Download of the torus mounter from S3 fails. Unauthorized.
