### ISSUE TITLE
Revamp AoE

### ISSUE THREAD

**Issue by barakmich** [coreos/torus#168]
It's been experimental for awhile. It's actually a cool trick; with the right drivers, it allows for other operating systems on the local network to have access to distributed block storage. It needs some love, or to be sunsetted.

**Comment by mikefedyk** [comment]
ATA over Ethernet?  It requires a flat layer 2 network.  I'd rather see iscsi support.

**Comment by barakmich** [comment]
Yeah, so would I. Fortunately, AoE is about a 12 page spec, and we have a motivated contributor.

On the other hand, there's nothing stopping one from providing the right block devices to a pod and using standard iscsi tools to serve it up. It's finding the right balance of the tooling.

**Comment by dan-and** [comment]
But it would be still a nice solution for home-labs and small devices (I have ARM devices in mind). 

So I will put a $20 bounty on it.
