### ISSUE TITLE
Threadsafe torus.File object access

### ISSUE THREAD

**Issue by barakmich** [coreos/torus#170]
Currently, *File objects are fairly lock intensive and aren't cleanly threadsafe.

This is a huge win to clean up, because then we can activate the support we already have for handling multiple NBD requests simultaneously, giving us a good boost in throughput.

**Comment by mikefedyk** [comment]
The subject makes me think of the clustered filesystem case with multiple writers from separate hosts or pods.

**Comment by barakmich** [comment]
Fair point

**Comment by barakmich** [comment]
Made clear and fixed with the race detector enabled and with #244. Note that this is spawning a new issue to make NBD more effective.
