### ISSUE TITLE
Expose Online Blockdev Snapshots

### ISSUE THREAD

**Issue by barakmich** [coreos/torus#182]
We already have the function to do so: https://github.com/coreos/torus/blob/master/block/metadata.go#L30 and we use it in `torusblk dump` -- adding `torusblock snap [save|restore]` is a relatively easy thing to do. And it's already copy-on-write and taken care of by being preserved from GC.

**Comment by philips** [comment]
I don't think I understand what the functional change would be here. Snapshots today take the volume offline?

**Comment by betawaffle** [comment]
No, currently there isn't an easy way to take and restore (or clone from) a snapshot. It would be nice to be able to take a snapshot and make a new volume from it.
