### ISSUE TITLE
Documentation/project-layout.md should be replaced by package documentation.

### ISSUE THREAD

**Issue by davecheney** [coreos/torus#194]
The documentation https://github.com/coreos/torus/blob/master/Documentation/project-layout.md should be moved to package documentation, eg. 
```go
// blockset provides an implementation of the BlockSet interface.
package blockset
```

Then the documentation shows up on godoc automagically and you don't have to keep a markdown file up to date as you move code around.

**Comment by xiang90** [comment]
One problem we had is that godoc is not discoverable on github. And most people will search on github. We should probably add doc.go but we probably should not remove the layout.md.

**Comment by davecheney** [comment]
Thanks
