### ISSUE TITLE
qemu driver

### ISSUE THREAD

**Issue by vtolstov** [coreos/torus#196]
Sometimes ago i want to write in go something like sheepdog storage, but now as i see coreos team already create it. 
Where i can find api of torus if i want to create plain qemu block driver to avoid usage of nbd?

**Comment by barakmich** [comment]
I need to write such a guide (that's #152) but for a quick overview, the `dump` and `load` commands are a pretty straightforward usage, starting at: https://github.com/coreos/torus/blob/master/cmd/torusblk/dump_load.go#L49 . `bf` in that function is a blockfile, which looks like a ReadWriteAtter interface in Go -- so your block driver can read and write to that as necessary.

**Comment by vtolstov** [comment]
2016-06-03 0:22 GMT+03:00 Barak Michener <notifications@github.com>:

> I need to write such a guide (that's #152
> <https://github.com/coreos/torus/issues/152>) but for a quick overview,
> the dump and load commands are a pretty straightforward usage, starting
> at:
> https://github.com/coreos/torus/blob/master/cmd/torusblk/dump_load.go#L49
> . bf in that function is a blockfile, which looks like a ReadWriteAtter
> interface in Go -- so your block driver can read and write to that as
> necessary.
>

This is internal things. For qemu driver torus need to be exposed some
endpoint (http, tcp).. As i understand this is not ready now...


-- 
Vasiliy Tolstov,
e-mail: v.tolstov@yoctocloud.net

**Comment by barakmich** [comment]
Hey, does #202 help you? There's an NBD server now that works with qemu

**Comment by vtolstov** [comment]
2016-06-04 1:45 GMT+03:00 Barak Michener <notifications@github.com>:

> Hey, does #202 <https://github.com/coreos/torus/pull/202> help you?
> There's an NBD server now that works with qemu
>

Thats nice! Thanks you. Now i'm try to test this, and if it works fine, i'm
write libvirt driver for torus.
Does torus suitable for block storage for vm like sheepdog and ceph?


-- 
Vasiliy Tolstov,
e-mail: v.tolstov@yoctocloud.net

**Comment by vtolstov** [comment]
Dont needed because torus supports nbd and scsi
