### ISSUE TITLE
Missing Blockset definition in Documentation/glossary.md

### ISSUE THREAD

**Issue by joehandzik** [coreos/torus#197]
Issue title is self-explanatory, but I'm not sure what the desired description would be. Here in the architecture document (https://github.com/coreos/torus/blob/master/Documentation/architecture.md) you lump the description of BlockLayer and Blockset together. Not sure if you would desire the same in the glossary or if there's a meaningful difference in their use.

**Comment by barakmich** [comment]
Yep, could do a better job of that. Slated for immediate fixing :)

**Comment by joehandzik** [comment]
@barakmich Thank you sir!
