### ISSUE TITLE
torusblk: De-confuse volume list and deletion

### ISSUE THREAD

**Issue by jason-riddle** [coreos/torus#206]
Creating a volume is simple enough

```
torusblk volume create
```

but there is no option to delete the volume.

**Comment by mdlayher** [comment]
You can use `torusctl volume delete` to delete volumes.  `torusctl volume list` is also available.

I do agree it's a little confusing that creating volumes is done in one place and deleting them is done in another.

**Comment by jason-riddle** [comment]
What I'm saying is the subcommand literally doesn't exist.

```
$ ./torus_v0.1.0_darwin_amd64/torusblk volume delete
Usage:
  torusblk volume [flags]
  torusblk volume [command]

Available Commands:
  create      create a block volume in the cluster

Global Flags:
  -C, --etcd string               hostname:port to the etcd instance storing the metadata (default "127.0.0.1:2379")
      --http string               HTTP endpoint for debug and stats
      --logpkg string             Specific package logging
      --read-cache-size string    Amount of memory to use for read cache (default "50MiB")
      --read-level string         Read replication level (default "block")
      --write-cache-size string   Maximum amount of memory to use for the local write cache (default "128MiB")
      --write-level string        Write replication level (default "all")

Use "torusblk volume [command] --help" for more information about a command.
```

**Comment by jason-riddle** [comment]
Ah sorry, just re-read what you wrote. Didn't notice you used <code>torusctl</code>.

**Comment by jason-riddle** [comment]
Why isn't there a <code>torusctl volume create</code>? Yes, this is very confusing.

**Comment by barakmich** [comment]
A couple options: Per volume-type commands, duplicate the commands -- having a global view in torusctl is useful, not confusing people is useful.

Best compromise is probably to let torusblk volume delete/list be equivalent to torusctl volume delete/list --type=block, roughly.
