### ISSUE TITLE
Connecting to secured etcd

### ISSUE THREAD

**Issue by jason-riddle** [coreos/torus#207]
The docs mention you can connect to etcd using the following

```
torusctl -C $ETCD_IP:2379
```

but if the connection is secured with SSL, it is not possible to pass in the cert location.

**Comment by barakmich** [comment]
Yeah, fair cop. Should probably do this and #176 at the same time; set up your SSL and config and you're off to the races.

**Comment by philips** [comment]
we should really be taking an etcd URL like `https://IP:port` now.

**Comment by xiang90** [comment]
@philips @barakmich Now etcd client is smart about http and https. If you specify https without key/cert, it will skip cert checking. But we still need to add key, cert options when user does want to verify the server.

**Comment by heyitsanthony** [comment]
@xiang90 I thought skipping cert checking as default behavior on 'https://' was a good idea but I've convinced myself it isn't worth the potential security problems. If the server's cert chain leads back to the client's root CA, it should still verify OK without providing any extra options.

**Comment by discordianfish** [comment]
Here is my PR to add tls auth: https://github.com/coreos/torus/pull/292

**Comment by discordianfish** [comment]
Guess this can be closed now!

**Comment by xiang90** [comment]
thanks for your contribution!
