### ISSUE TITLE
Use vendored state for Docker build

### ISSUE THREAD

**Issue by isubuz** [coreos/torus#231]
Building the docker image using the `Dockerfile` fails due to a compilation error on the etcd's` clientV3/client.go` module. 

```sh
root@ece14a1449e4:/go/src/github.com/coreos/torus# go install -v github.com/coreos/torus/cmd/torusd
github.com/coreos/etcd/clientv3
# github.com/coreos/etcd/clientv3
../etcd/clientv3/client.go:309: oldconn.State undefined (type *grpc.ClientConn has no field or method State)
../etcd/clientv3/client.go:311: oldconn.WaitForStateChange undefined (type *grpc.ClientConn has no field or method WaitForStateChange)
root@ece14a1449e4:/go/src/github.com/coreos/torus#
```

The `etcd/clientV3` module is referenced from `coreos/torus/block/etcd.go`. Seems like the `grpc.ClientConn` API has changed. 

Or am I missing something?

**Comment by Ulexus** [comment]
Having just encountered this with etcdv3, I can say that this problem is not with torus, but with the etcdv3 client library.

**Comment by gyuho** [comment]
This is an etcd issue https://github.com/coreos/etcd/issues/5561, where etcd clientv3 package is dependent on the old version of gRPC. We will fix.

Thanks.

**Comment by barakmich** [comment]
Modifying this issue: Use vendored state for Docker build.
