### ISSUE TITLE
Use existing glide binary if installed

### ISSUE THREAD

**Issue by odacremolbap** [coreos/torus#232]
[Getting started guide](https://github.com/coreos/torus/blob/master/Documentation/getting-started.md) seems to assume ```glide``` is in your path

```
git clone git@github.com:coreos/torus $GOPATH/src/github.com/coreos/torus
cd $GOPATH/src/github.com/coreos/torus
glide install
make
```

but then, the Makefile downloads its own binary to bin
```
bin/glide:
	@echo "Downloading glide"
	mkdir -p bin
	curl -L https://github.com/Masterminds/glide/releases/download/0.10.2/glide-0.10.2-$(GOOS)-$(GOARCH).tar.gz | tar -xz -C bin
	mv bin/$(GOOS)-$(GOARCH)/glide bin/glide
	rm -r bin/$(GOOS)-$(GOARCH)
````

should the Makefile check for an existing glide binary?
```
GLIDE:=$(shell command -v glide 2> /dev/null)

glide:
ifndef GLIDE
 ...
```

**Comment by ericchiang** [comment]
Ah, we should probably remove that "glide install" command in the document.

I personally like having Torus pinned to a specific version of glide, but I can see that using the host's glide could be convenient as well.

**Comment by barakmich** [comment]
Either can work. Pinning doesn't hurt, as long as it's part of our build process. 

I suppose it is possible that someday it may be harder to recreate builds, but Go vendoring presupposes the existence of Github anyway, in most cases. We keep the lockfile, fix the guide, grab glide as-is in the Makefile, and revisit if it becomes onerous.
