### ISSUE TITLE
TestInterfaceClose fails on OSX

### ISSUE THREAD

**Issue by alpe** [coreos/torus#237]
```
--- FAIL: TestInterfaceClose (0.00s)
	interface_test.go:15: *net.OpError route ip+net: no such network interface
FAIL
...
```
On: OSX Yosemite + El Capitan
`go version go1.6.2 darwin/amd64`

The interface is called `lo0` instead but it would still fail with ` *os.PathError open /dev/bpf0: permission denied` on my boxes.

What are the supported OS? I can provide a patch to deactivate the test via build tag for `darwin` if it makes sense.

**Comment by barakmich** [comment]
@mdlayher Thoughts? This looks like we're trying to do BPF on Darwin.

**Comment by mdlayher** [comment]
Yep, my guess is that BPF can't be used on Darwin without root.  A possible resolution would be to check for `syscall.EPERM` when loading a BPF filter and then disabling the filter and using userspace packet filtering instead.

**Comment by mdlayher** [comment]
Submitted a PR to fix the BPF issue.  As far as the `lo` vs. `lo0` thing, we can either make a simple `if/else` that checks for the platform, or do something smarter like listing all interfaces, checking which one has IP address `127.0.0.1`, and use that.
