### ISSUE TITLE
sheepdog

### ISSUE THREAD

**Issue by joeblew99** [coreos/torus#245]
This is really great. The ability to develop SAN like storage using K8, docker and golang opens things up.
The harsh climate on Hacker News is to be expected - your treading on turf.

Have you seen this:
https://github.com/sheepdog/sheepdog

It is using https://github.com/corosync/corosync for sync.
Lots of good algos here.

i found a golang client here:
https://github.com/neurodrone/picard

**Comment by vtolstov** [comment]
Corosync not so stable like etcd in my tests (firstly you need corosync 2..x) (i'm use sheepdog).
Also it uses multicast and udpu not so stable (may be i'm wrong).

**Comment by joeblew99** [comment]
@vtolstov Great to get that feedback.

i was just reading how Corosync uses Pacemaker for sync aspects.

I am personally really curious about AoE
https://en.wikipedia.org/wiki/ATA_over_Ethernet

Spec:
http://brantleycoilecompany.com/AoEr11.pdf

golang implementation:
https://github.com/mdlayher/aoe

The reason i like AOE is because, when i worked with it a few years ago, compared to the other offerings it is simple and reasonable open. No special Hardware in terms of cards or transport.

**Comment by vtolstov** [comment]
My use case - virtual machines. So in case of AoE i need to attach devices to linux host and use in qemu block device. In this case qemu->linux host->network->torus

In case of using nbd i have qemu->network(nbd)->torus
So this is not need to copy data to kernel and can give more speed.

**Comment by joeblew99** [comment]
There is ndbd golang code going into the repo from what I see on the PR's.

I really need to get a instance up to try this out.

**Comment by ericchiang** [comment]
Since this is the issue tracker for Torus is there a specific issue you're raising? For example aret there features in sheepdog you'd like to see in Torus?

There might be better forums for these kinds of discussions :)

**Comment by vtolstov** [comment]
From sheepdog may be useful custom redundancy level per volume,that for
this volume overrides cluster setting.
So for most of people I have 4 copies ,and for some specific volumes 1 copy
if data can be easy recovered via application.
8 Июн 2016 г. 19:44 пользователь "Eric Chiang" <notifications@github.com>
написал:

**Comment by joeblew99** [comment]
I will close this. It should be on the Google groups
