### ISSUE TITLE
weighted consistent hashing algorithm issues in ring.ketama

### ISSUE THREAD

**Issue by sgotti** [coreos/torus#246]
I noticed that, since the `ring.GetPeers` function have to return all the (ring ordered) peers, the current weighted consistent hashing algorithm won't always satisfy this.

Example:

Create two 20GiB peers and 1 100MiB peer. The first two will have a weight of 1024 while the smaller one will have a weight of 5. With the current weighted consistent hashing algorithm implementation (`github.com/serialx/hashring`) there'll be no point in the ring for this peer and `ring.GetPeers` will always fail with error `couldn't get sufficient nodes` making all the cluster stop working (noticed this adding a smaller peer to a working cluster).

One possible solution will be:

* Change the consistent hashing algorithm implementation to dynamically increase its number of points so it can reserve at least one point in the ring for the lower weight peer. As a downside increasing the number of points will increase the time required to get all the peers. Another optimization will be to get the next peers only when required (implementing an iterator)

Perhaps there're other weighted consistent hashing algorithms implementations that satisfy the need to retrieve all the peers in the ring.

**Comment by sgotti** [comment]
I'd like to experiment if google jump consistent hash can be used as a weighted consistent hash (playing with the number of buckets) and return the ordered list of peers. Something like [this](https://github.com/dgryski/go-shardedkv/blob/master/choosers/jump/jump.go) but also with weights.

**Comment by barakmich** [comment]
@sgotti Good catch. I was under the impression that the 100MB peer still had a point on the ring; if it doesn't that's a problem with the underlying hash.

So, I propose a double-pronged attack:
1) Fix the assumption, by hook or by crook (by fixing the hashring package or by appending the non-existent nodes to the end always)
2) Experiment with new rings and hashes, which is a long term plan anyway. Finding a better one that's simple enough in the short term is fine by me.

**Comment by barakmich** [comment]
@sgotti If you want to spawn a new issue for experimenting with jump consistent hashes and the like, go for it :) This becomes the "fix the ketama" issue.
