### ISSUE TITLE
'wipe' command crashes whole cluster 

### ISSUE THREAD

**Issue by Ramzec** [coreos/torus#267]
'panic: replacing old ring with ring in the past!'

It is because after removing metadata from etcd the version of ring becomes zero

**Comment by barakmich** [comment]
That's true. I'm not sure if this is a bug or a feature; it completely wipes the consistent metadata. What would you have it do?

**Comment by Ramzec** [comment]
I think 'panic' is the last what it should do :-)

**Comment by barakmich** [comment]
So there's wiping data, and there's wiping metadata. If you meant to delete all volumes and start from 0, that's one thing, and a feature request. Intentionally killing all metadata that coordinates the cluster in etcd, a flag behind a very large warning (either typing `YES` or `--yes-i-am-sure`)  -- crashing is actually a fair response for any nodes still connected.
