### ISSUE TITLE
create-block command not found

### ISSUE THREAD

**Issue by 329379172** [coreos/torus#274]
```
./bin/torusctl volume create-block myVolume 10GiB
```

 i run this command,i found create-block command not found.

then i run --help, found only these commands can be run.

```
./bin/torusctl volume list
./bin/torusctl volume delete
```

**Comment by barakmich** [comment]
Hi! 

Good catch, that just changed yesterday with #272 -- the docs in the release package are still correct, but the latest has changed. For the older walkthrough, check https://github.com/coreos/torus/tree/v0.1.0

Cheers!
