### ISSUE TITLE
How to reset the Kubernetes cluster with Torus

### ISSUE THREAD

**Issue by FaKod** [coreos/torus#288]
Hi, I am using Torus (v0.1.1) as a volume plugin in a Kubernetes (v1.2.3) Cluster with Postgres and Mongo volumes. 
After creating my Pods, I get some errors like "status: Failure, reason: Unit torus-dev-nbd0.service already exists." etc. However, I am unable to somehow reset the cluster, to do the tests again. What do I have to do to reset the Torus setup (except recreating the whole cluster)?

([k8s-node.j2](https://gist.github.com/FaKod/51f7af6a541a31f15ac28062914b691e) is my Ansible node template, that I use to create the cluster)

**Comment by barakmich** [comment]
I think we chatted some days ago on IRC, but just double checking how that worked. 

Yeah, NBD is kind of a piece of work, and shortly you'll see an alternative for modern kernels (based on our new lib over at https://github.com/coreos/go-tcmu ). Killing the service with `systemctl kill torus-dev-nbd0.service` is sufficient, but, yeah, NBD disconnection, while it's gotten better, is still flaky with that kernel module sometimes.
