### ISSUE TITLE
nbd: Gracefully degrade for older kernels that return errors on NBD_SET_FLAGS

### ISSUE THREAD

**Issue by zhengxiaochuan-3** [coreos/torus#295]
I followed https://github.com/coreos/torus/blob/master/Documentation/getting-started.md 

all things go well utill step 7 , i get errors like this : 

[root@A01-R14-I152-74 torus_v0.1.1_linux_amd64]# modprobe nbd
[root@A01-R14-I152-74 torus_v0.1.1_linux_amd64]# ./torusblk --etcd 127.0.0.1:2379 nbd myVolume /dev/nbd0
Connected to /dev/nbd0
error from nbd server: ioctl NBD_SET_FLAGS /dev/nbd0: inappropriate ioctl for device

info : 

[root@A01-R14-I152-74 torus_v0.1.1_linux_amd64]# ./torusctl ring get
Ring: Ketama
Replication:2
Peers:
    uuid:"09b391b9-57c2-11e6-a52f-246e96035730" address:"http://127.0.0.1:40001" last_seen:1470040187798196068 total_blocks:40960 rebalance_info:<last_rebalance_finish:1470040187192760131 > protocol_version:1 
    uuid:"ee8b0565-57c1-11e6-9d80-246e96035730" address:"http://127.0.0.1:40000" last_seen:1470040185617222030 total_blocks:40960 rebalance_info:<last_rebalance_finish:1470040185057607298 > protocol_version:1

**Comment by barakmich** [comment]
Hi! So that's an interesting error -- what distro/kernel are your running?

**Comment by zhengxiaochuan-3** [comment]
CentOS release 6.6 (Final) 
2.6.32-504.16.2.el6.x86_64 
@barakmich

**Comment by barakmich** [comment]
That's a bit on the older side. I dug into this, and the reason it's causing an error is that the kernel doesn't understand the TRIM or FLUSH ioctl setting. 

We can probably work with this, but it's not on the critical path. Converting this issue into a low-priority bug. If someone would like to catch these errors (in internal/nbd) and gracefully downgrade for older kernel versions, I'd be happy to take the change (it's a relatively simple patch, anyway).

**Comment by Lax77** [comment]
Seeing the same issue on. Tried out on 2 servers and both have failed with same issue. Is Kernel version 3.10 is old too?

Here are the version of OS & Kernel I am using. 
CentOS Linux release 7.2.1511
Kernel Release: 3.10.0-327.13.1.el7.x86_64

**Comment by lethe3000** [comment]
meet similar error on Ubuntu 14.04
Linux ubuntu-102 4.2.0-27-generic #32~14.04.1-Ubuntu SMP Fri Jan 22 15:32:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

```
./torusblk nbd myVolume /dev/nbd2
2016-10-26 14:41:59.058348 I | torus: creating metadata service: etcd
2016-10-26 14:41:59.079474 I | torus: 42c35e5b-9b46-11e6-939d-086266307222: 1
2016-10-26 14:41:59.079509 I | torus: 5b7ff3f7-9b46-11e6-ada0-086266307222: 1
2016-10-26 14:41:59.079520 I | torus: 96af0518-9b45-11e6-866d-086266307222: 1
2016-10-26 14:41:59.079860 I | torus: creating blockstore: temp
2016-10-26 14:41:59.088828 I | torus: 42c35e5b-9b46-11e6-939d-086266307222: 1
2016-10-26 14:41:59.088915 I | torus: 5b7ff3f7-9b46-11e6-ada0-086266307222: 1
2016-10-26 14:41:59.088941 I | torus: 96af0518-9b45-11e6-866d-086266307222: 1
Connected to /dev/nbd2
error from nbd server: ioctl NBD_SET_FLAGS /dev/nbd2: inappropriate ioctl for device
```
maybe the cause of [issue 367](https://github.com/coreos/torus/issues/367)
