### ISSUE TITLE
close() by defer are not called when os.Exit(1)

### ISSUE THREAD

**Issue by nak3** [coreos/torus#333]
`os.Exit(1)` doesn't return, so `defer close()` is not called. For example, [nbdAction()](https://github.com/coreos/torus/blob/v0.1.2/cmd/torusblk/nbd.go#L42-L94) have them.

Please refer to https://gobyexample.com/exit

**Comment by amy** [comment]
Hello! Wanted to discuss how to handle this to potentially contribute.

```
func doTheStuff() int {
    defer fmt.Println("!")

    return 3
}

func main() {
    os.Exit(doTheStuff())
}
```
http://stackoverflow.com/questions/27629380/how-to-exit-a-go-program-honoring-deferred-calls

Is this solution something you think is appropriate?

**Comment by nak3** [comment]
Sorry, that's not what I expected. I will send the patch later.
