### ISSUE TITLE
Erasure Coding

### ISSUE THREAD

**Issue by betawaffle** [coreos/torus#7]
We should use [Reed-Solomon](https://en.wikipedia.org/wiki/Reed%E2%80%93Solomon_error_correction) or [something similar](https://research.facebook.com/publications/300734513398948/xoring-elephants-novel-erasure-codes-for-big-data/) to reduce replication storage overhead and increase resiliency to data loss.

Also, [this](https://code.facebook.com/posts/536638663113101/saving-capacity-with-hdfs-raid/) may be useful.

**Comment by vtolstov** [comment]
I recommend https://github.com/klauspost/reedsolomon it have apotimized version for avx2, sse3/sse4.
Also it easy to use and able to configure  number of data and parity shards
